// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebServiceAppOS.Data;

namespace WebServiceAppOS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190623225140_Acreditaciones")]
    partial class Acreditaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WebServiceAppOS.Models.Acreditacion", b =>
                {
                    b.Property<string>("Matricula")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Aceptado");

                    b.Property<decimal>("CostoTotal");

                    b.Property<int>("Creditos");

                    b.HasKey("Matricula");

                    b.ToTable("Acreditaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
